version: "3.9"

services:

  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./resources/grafana/provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./resources/grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./resources/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    depends_on:
      - mysql
    networks:
      - mysern-app

  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        - dbdata:/var/lib/mysql
    networks:
      - mysern-app

networks:
  mysern-app:
    driver: bridge

volumes:
    dbdata: